version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: "otus/nginx"
    container_name: "otus-nginx-${VERSION}"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./www:/www/mysite.local
      - ${NGINX_LOGS_PATH}:/var/log/nginx/
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: "otus/fpm"
    container_name: "otus-php-${VERSION}"
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    env_file:
      - .env
    volumes:
      - ./www:/www/mysite.local
      - ${PHP_LOGS_PATH}:/var/log/fpm-php.www.log
    networks:
      - app-network
    depends_on:
      - postgresql
      - rabbitmq

  postgresql:
    image: postgres:14.7-alpine
    container_name: "otus-postgresql-${VERSION}"
    environment:
      POSTGRES_USER: hukimato
      POSTGRES_PASSWORD: hukimato
      POSTGRES_DB: hukimato
      PGDATA: "/var/lib/postgresql/data/pgdata"
#    ports:
#      - "5432:5432"
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: "otus-rabbitmq-${VERSION}"
#    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
#    ports:
#      - "15672:15672"
    volumes:
      - ${RABBITMQ_PATH}:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge