name: "Start queue consumer manually"
on: 
  workflow_dispatch 

jobs: 
  run-consumer:
    runs-on: ubuntu-latest
    steps:
      - name: "Run current php worker"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script: |
            docker exec -itd otus-php-current php bin/app.php
